### ISSUE TITLE
can i make more custom error class?

### ISSUE THREAD

**Issue by chocholand** [jeffijoe/fejl#1]
```
static assert(data1, data2, message) {
    if (data1 !== data2) {
      throw new this(message)
    }
  }
```
I use this code in js.
but in ts
![2018-10-08 11 52 11](https://user-images.githubusercontent.com/6572227/46616301-32382880-cb55-11e8-8671-40f5546b550d.png)

**Comment by jeffijoe** [comment]
You can't override `assert` directly, but you can add your own. Just don't call it `assert`. 😄
