### ISSUE TITLE
Native ESM Support

### ISSUE THREAD

**Issue by saghen** [jeffijoe/fejl#18]
Currently when using ESM in Node, imports have to be done like so.
```js
import fejl from "fejl";
const { NotImplemented } = fejl
```

**Comment by jeffijoe** [comment]
I haven’t used ESM in Node yet, what’s required to make it happen?

**Comment by saghen** [comment]
[This is a pretty solid reference](https://2ality.com/2019/10/hybrid-npm-packages.html) of how to switch over. Essentially, two packages can be included. One for CJS and one for ES2015/ESM.

https://github.com/jeffijoe/fejl/blob/master/tsconfig.json#L9-L10
Both of these lines would need to be changed to es2015 for the ESM compilation.

**Comment by jeffijoe** [comment]
I’d have to set up Rollup for this. I’m ok with it, but I don’t know when I will get to it.

**Comment by saghen** [comment]
I actually managed to do it without Rollup. I'll have the Pull Request up for review in just a moment.

**Comment by saghen** [comment]
I've consuted with devsnek, a node contributer, about this issue. He also wasn't a fan of dual packages but was overruled on the issue. Regardless, he pointed me to a tool that can automate the creation of ESM wrappers for CJS. https://github.com/addaleax/gen-esm-wrapper

Would you be interested in taking another crack at this? It should solve the dual package issue that you noted before.

**Comment by jeffijoe** [comment]
Go for it! Will it also prevent the warning about experimental conditional exports?

**Comment by saghen** [comment]
Yeah, for now we can just use `fejl/esm`. The first phase was removing the flag and second is removing the warning. https://github.com/nodejs/node/issues/31819

**Comment by saghen** [comment]
I'm pretty swamped with work right now but I should be able to get around to it on the weekend

**Comment by jeffijoe** [comment]
Sounds good.
