### ISSUE TITLE
Set Custom Properties in assert()

### ISSUE THREAD

**Issue by johannesschobel** [jeffijoe/fejl#4]
Dear @jeffijoe ,
this package looks really nice - i like the approach of proving `assert()` methods! When browsing through the code, i thought, that it may be useful to allow overriding (or even setting) specific properties within the `assert()` methods...

```ts
function updateUser(user) {
  ValidationException.assert(user.name, 'Username is required', { url: 'https://my-fancy-endpoint/api/user/4711', method: 'POST', param: 'username' })
}
```

What do you think? Would it be benefitial to add this additional parameter?
All the best

**Comment by jeffijoe** [comment]
Absolutely! Same applies to `makeAssert`. The constructors of the errors accept a 2nd parameter that does this, so it's simply a matter of adding that to the assert methods. 😄

Would you like to open a PR?

**Comment by johannesschobel** [comment]
yeah, i already checked, that you just need to pass the param down to the next classes.. 
sure, i can add those params in a PR, but i need some time because i have a hell of work to do here at university :worried: 

for which methods do you want the additional params? I would make them optional, right?
* `assert`
* `makeAssert`

**Comment by jeffijoe** [comment]
Yeah I believe that's everywhere. Yes, optional. 😄
