### ISSUE TITLE
ErrorBag and BaseError

### ISSUE THREAD

**Issue by johannesschobel** [jeffijoe/fejl#9]
Dear @jeffijoe ,

thanks a lot for this awesome package. I toyed a bit around, and i quite liked it!
However, i came across the following use-case i would like to discuss with you.

I would like to introduce some kind of `ErrorBags` , where i can add errors. Consider, for example, the following situation: The api consumer submits data and the API answers with a lot of exceptions, based on the errors the user made. For example:
```js
{
  status: 400,
  errors: [
    {
      type: "BadRequest",
      message: "E-Mail not properly formatted",
      status: 400,
      meta: {
        timestamp: 1234567890,
        url: "some/url/here",
      },
      attribute: "user.email"
    },
    {
      // another error here
    },
    {
      // and another error here
    }
  ]
}
```

It would be benefitial to define the class as follows:
```ts
export class ErrorBag {
  errors: BaseError[];
}
```
however, the `BaseError` must be properly typed because it is generic. How can i solve this issue? Am i missing something? I most likely cannot add the typing in the `ErrorBag` itself, as the `ErrorBag` may contain different errors (e.g, validation errors, authentication errors and whatever-other-type of errors)..

All the best and thanks a lot for your time / help!

PS: Would it be good to add this to the package as well? What do you think?

**Comment by jeffijoe** [comment]
You can use `errors: BaseError<{}>`, replace `{}` with whatever shared props all your errors may have. 😄

**Comment by johannesschobel** [comment]
wow, that was fast..
what do you think about the `ErrorBag` in general? Should / would that be good to add it to the `fejl` package?

**Comment by jeffijoe** [comment]
I don't think it warrants being included in a library, it's just an array of errors. 😄

**Comment by johannesschobel** [comment]
basically, yes.. however, i would also add a "status" as well (because you may want to have an additional status code for the response if the errorBag holds different types of errors) and meta information..

**Comment by johannesschobel** [comment]
thanks a lot for your time helping me with this issue!

**Comment by jeffijoe** [comment]
No problem!
